---
abstract: 'Read and write OLE storage files.'
author:
  - 'Kawai Takanori (kwitknr@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OLE-Storage_Lite
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
version: '0.22'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
